# PyTorch
[Getting Started Tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [1]:
from __future__ import print_function
import torch

In [3]:
# empty matrix, uninitialized
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000e+00, -2.5244e-29,  0.0000e+00],
        [-2.5244e-29,  1.2612e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [5]:
# randomly initialized matrix
x = torch.rand(5,3)
print(x)

tensor([[0.3659, 0.1156, 0.1333],
        [0.0028, 0.2261, 0.5210],
        [0.8467, 0.9021, 0.8045],
        [0.5424, 0.5832, 0.7609],
        [0.6666, 0.5422, 0.1336]])


In [8]:
# matrix filled with zeros and dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
# tensor directly from data

In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])
